### ISSUE TITLE
Following the WP 5.2 update, <?= should be allowed

### ISSUE THREAD

**Issue by nyordanov** [envato/envato-theme-check#44]
[WP 5.2 increased the minimum required PHP version to 5.2](https://wordpress.org/about/requirements/). The short echo tag (`<?=`) is always available as of PHP 5.4: https://www.php.net/manual/en/language.basic-syntax.phptags.php

**Comment by Stephen-Cronin** [comment]
Our current stance is that we don't allow `<?=`. Part of the reasoning was due to WP's PHP version (no longer an issue as you point out now that PHP5.6 is the minimum), but it was also due to confusion we've seen in the past with some authors thinking it means that `<?` is allowed. 

We may revisit this in future (ie I'll add it to the list to be considered for next time we update the requirements), but for now we don't allow it. I'll close this, as this is for the Theme Check plugin not the requirements. Thanks for raising it though.
